### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by khanhnguyenq** [khanhnguyenq/smile#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to view the landing page, sign-in if they already have an account, or sign-up if they do not.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="187" alt="Screenshot 2024-01-18 at 06 48 29" src="https://github.com/khanhnguyenq/smile/assets/114459075/5765c6f6-4f6d-4f50-8435-c45c3431a474">
<img width="186" alt="Screenshot 2024-01-18 at 06 48 49" src="https://github.com/khanhnguyenq/smile/assets/114459075/7adb843b-3b7d-4100-9c5f-8ed2d60da58c">
<img width="188" alt="Screenshot 2024-01-18 at 06 49 12" src="https://github.com/khanhnguyenq/smile/assets/114459075/072ed603-7f12-4641-857e-1ad873ca158d">
<img width="185" alt="Screenshot 2024-01-18 at 06 49 27" src="https://github.com/khanhnguyenq/smile/assets/114459075/29d59d7a-d786-41c5-9058-fb5d33244486">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include `float` for `'longitude'` and `'latitude'` instead of `integer`
- [x] Update `data.sql` to insert `'username'`, `'name'`, and `'hashedPassword'` into the `users` table

### ☁️ Server Tasks

- [x] Update `server.ts` to make calls to the API endpoint to `sign-up` a user by gathering data from the client form
     - [x] Handle error regarding username and password
- [x] Update `server.ts` to make calls to the API endpoint to `sign-in` a user by gathering data from the client form
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display the `logo` in the `navbar`
- [x] Create the `carousel` component
- [x] Create the component for the `sign-up` process
- [x] Create the component for the `sign-in` process
- [x] Create the component for the `search bar`

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
