### ISSUE TITLE
Feature: User can select a theme park from a list

### ISSUE THREAD

**Issue by khanhnguyenq** [khanhnguyenq/smile#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see theme parks based on location or by filtering by name

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user logged in, they will be able to use their current location to look for the closest theme parks. They can also look up a theme park by name. If the theme park does not exist in the database, the user will see an error.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="184" alt="Screenshot 2024-01-25 at 09 20 12" src="https://github.com/khanhnguyenq/smile/assets/114459075/294b9d8e-857e-40ff-864f-432db1014b27">
<img width="184" alt="Screenshot 2024-01-25 at 09 20 20" src="https://github.com/khanhnguyenq/smile/assets/114459075/d1bf5bae-674d-4d1a-bca7-b56d98c02536">
<img width="182" alt="Screenshot 2024-01-25 at 09 20 32" src="https://github.com/khanhnguyenq/smile/assets/114459075/c8200d91-5cde-4a4d-8bbe-de8463b42607">
<img width="182" alt="Screenshot 2024-01-25 at 09 20 40" src="https://github.com/khanhnguyenq/smile/assets/114459075/f4ea556f-1dd6-4e5b-ab74-e061fbe1384a">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `data.ts` to read all available parks from database
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create `GetUserLocation` component to utilize built in functionalities to obtain location
- [x] Create `ParksByDistance` component to display theme parks based on the user's location
- [x] Update `LoggedIn` component to incorporate `GetUserLocation` and `ParksByDistance` components
- [x] Create `SearchResults` page to display results based on the user's search

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
